name: flutter_application_1
description: "A new Flutter project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
<<<<<<< HEAD
  photo_view: ^0.15.0
=======
  pie_chart: ^5.4.0
>>>>>>> 8d9b8489fb21a1c8891ed85de8fa624d5a86c987

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/load_screen.png
<<<<<<< HEAD
    - assets/images/grechka.png
    - assets/images/meals.png
    - assets/images/pelmeni.png
    - assets/images/borsch.png
    - assets/images/democr.png  
    - assets/images/most.png
    - assets/images/breackfast.png
    - assets/images/potatoes.png
    - assets/images/plans/1_plan.png
    - assets/images/plans/2_plan.png
    - assets/images/plans/3_plan.png
=======
    - assets/images/
    - assets/icons/
>>>>>>> 8d9b8489fb21a1c8891ed85de8fa624d5a86c987

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700